# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Firebase' do

pod 'Firebase', '>= 2.4.2'

end

target 'FirebaseTests' do

end

target 'FirebaseUITests' do

end

